-- V8.1: where postings come from, and when each posting was first and last seen.
--
-- A source is identified by the label its records carry (jobs.source, e.g. 'synthetic-dev'),
-- which stays on jobs as the natural key of the existing (source, source_url) uniqueness.
-- Everything else about a source lives here once, and jobs point to it.

CREATE TABLE job_sources (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    code                  VARCHAR(100) NOT NULL,
    name                  VARCHAR(150) NOT NULL,
    -- How the source is delivered. File types today; API is reserved for later sources.
    source_type           VARCHAR(20)  NOT NULL DEFAULT 'OTHER',
    -- An inactive source's records are rejected by the ETL; its existing jobs stay.
    active                BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_ingested_at      TIMESTAMPTZ,
    last_run_execution_id BIGINT,

    CONSTRAINT pk_job_sources PRIMARY KEY (id),
    CONSTRAINT uq_job_sources_code UNIQUE (code),
    CONSTRAINT ck_job_sources_type CHECK (source_type IN ('FILE_JSON', 'FILE_CSV', 'API', 'OTHER'))
);

-- Existing postings: one source per distinct label.
INSERT INTO job_sources (code, name, created_at, last_ingested_at)
SELECT source, source, min(created_at), max(updated_at) FROM jobs GROUP BY source;

ALTER TABLE jobs
    ADD COLUMN source_id        BIGINT,
    -- The source's own id for the posting, when it gives one.
    ADD COLUMN source_job_id    VARCHAR(200),
    ADD COLUMN first_seen_at    TIMESTAMPTZ,
    ADD COLUMN last_seen_at     TIMESTAMPTZ,
    -- The ETL run (BATCH_JOB_EXECUTION id) that last saw the posting.
    ADD COLUMN last_seen_run_id BIGINT;

UPDATE jobs j
SET source_id = s.id, first_seen_at = j.created_at, last_seen_at = j.updated_at
FROM job_sources s
WHERE s.code = j.source;

ALTER TABLE jobs
    ALTER COLUMN source_id SET NOT NULL,
    ALTER COLUMN first_seen_at SET NOT NULL,
    ALTER COLUMN first_seen_at SET DEFAULT now(),
    ALTER COLUMN last_seen_at SET NOT NULL,
    ALTER COLUMN last_seen_at SET DEFAULT now(),
    -- A source with postings cannot be deleted; deactivate it instead.
    ADD CONSTRAINT fk_jobs_source FOREIGN KEY (source_id) REFERENCES job_sources (id) ON DELETE RESTRICT;

CREATE INDEX idx_jobs_source_id ON jobs (source_id);
-- One posting per source id within a source, where the source gives ids.
CREATE UNIQUE INDEX uq_jobs_source_job_id ON jobs (source_id, source_job_id) WHERE source_job_id IS NOT NULL;

-- Every insert is linked to its source, whoever inserts: the ETL, a manual load, a test.
CREATE FUNCTION jobs_link_source() RETURNS trigger AS $$
BEGIN
    IF NEW.source_id IS NULL THEN
        INSERT INTO job_sources (code, name) VALUES (NEW.source, NEW.source) ON CONFLICT (code) DO NOTHING;
        SELECT id INTO NEW.source_id FROM job_sources WHERE code = NEW.source;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_jobs_link_source BEFORE INSERT ON jobs
    FOR EACH ROW EXECUTE FUNCTION jobs_link_source();

-- Per run, per source: what the ETL loaded and what it saw again. Read with Spring Batch's
-- own execution tables for status and timing, as etl_run_metrics is.
CREATE TABLE etl_run_sources (
    job_execution_id   BIGINT NOT NULL,
    source_id          BIGINT NOT NULL,
    records_loaded     BIGINT NOT NULL DEFAULT 0,
    records_seen_again BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT pk_etl_run_sources PRIMARY KEY (job_execution_id, source_id),
    CONSTRAINT fk_etl_run_sources_execution FOREIGN KEY (job_execution_id)
        REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID) ON DELETE CASCADE,
    CONSTRAINT fk_etl_run_sources_source FOREIGN KEY (source_id) REFERENCES job_sources (id) ON DELETE CASCADE
);

CREATE INDEX idx_etl_run_sources_source ON etl_run_sources (source_id, job_execution_id DESC);

-- The feed a run read: the file name only (never a path) and its format.
ALTER TABLE etl_run_metrics
    ADD COLUMN feed_name VARCHAR(255),
    ADD COLUMN feed_type VARCHAR(20);
