-- Core schema for the Job Market Intelligence Platform.
--
-- Reference tables (companies, locations, skills) are created before jobs and
-- job_skills because those depend on them.
--
-- Naming conventions: pk_ primary keys, fk_ foreign keys, uq_ unique constraints
-- and unique indexes, ck_ check constraints, idx_ plain indexes.


-- ---------------------------------------------------------------------------
-- companies
-- ---------------------------------------------------------------------------
CREATE TABLE companies (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(255) NOT NULL,
    industry   VARCHAR(100),
    website    VARCHAR(255),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT pk_companies PRIMARY KEY (id)
);

-- Company name is the natural key. Indexing lower(name) keeps the original
-- casing for display while preventing "Google" / "GOOGLE" duplicates, and lets
-- the ETL resolve a company with a case-insensitive lookup that uses the index.
CREATE UNIQUE INDEX uq_companies_name ON companies (lower(name));


-- ---------------------------------------------------------------------------
-- locations
-- ---------------------------------------------------------------------------
CREATE TABLE locations (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    city       VARCHAR(120),
    state      VARCHAR(120),
    country    VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT pk_locations PRIMARY KEY (id)
);

-- Country first so the index also serves country-level and country+state
-- analytics as a prefix scan.
--
-- NULLS NOT DISTINCT is essential here: city and state are frequently unknown,
-- and under the default NULL semantics ('London', NULL, 'UK') would never equal
-- itself, letting the same location be inserted without limit.
CREATE UNIQUE INDEX uq_locations_country_state_city
    ON locations (lower(country), lower(state), lower(city)) NULLS NOT DISTINCT;


-- ---------------------------------------------------------------------------
-- skills
-- ---------------------------------------------------------------------------
CREATE TABLE skills (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(100) NOT NULL,
    category   VARCHAR(50),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT pk_skills PRIMARY KEY (id)
);

CREATE UNIQUE INDEX uq_skills_name ON skills (lower(name));


-- ---------------------------------------------------------------------------
-- jobs
-- ---------------------------------------------------------------------------
CREATE TABLE jobs (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    title               VARCHAR(300)  NOT NULL,
    company_id          BIGINT        NOT NULL,
    location_id         BIGINT,
    description         TEXT,
    employment_type     VARCHAR(20),
    experience_min      SMALLINT,
    experience_max      SMALLINT,
    salary_min          NUMERIC(12, 2),
    salary_max          NUMERIC(12, 2),
    currency            CHAR(3),
    posted_date         DATE,
    source              VARCHAR(50)   NOT NULL,
    source_url          TEXT,
    content_fingerprint CHAR(64)      NOT NULL,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT pk_jobs PRIMARY KEY (id),

    -- No ON DELETE action: a company or location that still has jobs must not
    -- be removed.
    CONSTRAINT fk_jobs_company  FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT fk_jobs_location FOREIGN KEY (location_id) REFERENCES locations (id),

    CONSTRAINT uq_jobs_content_fingerprint UNIQUE (content_fingerprint),

    -- Employment type is normalised to this vocabulary by the ETL, never stored
    -- as the raw value the source happened to use.
    CONSTRAINT ck_jobs_employment_type CHECK (
        employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', 'TEMPORARY', 'FREELANCE')
    ),

    -- A NULL operand makes a CHECK evaluate to NULL, which counts as satisfied,
    -- so these constrain only the values that are actually known.
    CONSTRAINT ck_jobs_experience_min_non_negative CHECK (experience_min >= 0),
    CONSTRAINT ck_jobs_experience_range            CHECK (experience_max >= experience_min),
    CONSTRAINT ck_jobs_salary_min_non_negative     CHECK (salary_min >= 0),
    CONSTRAINT ck_jobs_salary_range                CHECK (salary_max >= salary_min),
    CONSTRAINT ck_jobs_currency_format             CHECK (currency ~ '^[A-Z]{3}$'),

    -- A salary without a currency cannot be compared or aggregated, so reject it.
    CONSTRAINT ck_jobs_currency_required CHECK (
        currency IS NOT NULL OR (salary_min IS NULL AND salary_max IS NULL)
    )
);

COMMENT ON COLUMN jobs.content_fingerprint IS
    'SHA-256 hex digest of the normalised (title, company, location, posted_date) tuple. '
    'Identifies the same posting arriving from different sources, which (source, source_url) cannot catch.';

COMMENT ON COLUMN jobs.source IS
    'Identifier of the dataset or API the posting was ingested from.';

-- PostgreSQL does not index foreign keys automatically. Both of these carry
-- company and location analytics as well as the joins behind job search.
CREATE INDEX idx_jobs_company_id  ON jobs (company_id);
CREATE INDEX idx_jobs_location_id ON jobs (location_id);

-- Descending because every trend and "recent postings" query reads newest first.
CREATE INDEX idx_jobs_posted_date ON jobs (posted_date DESC);

-- Second duplicate defence: the identical posting re-ingested from the same
-- source. Partial, because a source that supplies no URL must not collapse all
-- of its postings into one row.
CREATE UNIQUE INDEX uq_jobs_source_url ON jobs (source, source_url) WHERE source_url IS NOT NULL;


-- ---------------------------------------------------------------------------
-- job_skills
-- ---------------------------------------------------------------------------
CREATE TABLE job_skills (
    job_id   BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,

    -- The composite key is the whole row: it is the primary key, and it makes
    -- the same skill impossible to attach to a job twice.
    CONSTRAINT pk_job_skills PRIMARY KEY (job_id, skill_id),

    CONSTRAINT fk_job_skills_job   FOREIGN KEY (job_id)   REFERENCES jobs (id)   ON DELETE CASCADE,
    CONSTRAINT fk_job_skills_skill FOREIGN KEY (skill_id) REFERENCES skills (id) ON DELETE CASCADE
);

-- The primary key already serves lookups by job_id. Skill demand analytics read
-- the other way round ("which jobs require skill X"), which needs its own index.
CREATE INDEX idx_job_skills_skill_id ON job_skills (skill_id);


-- ---------------------------------------------------------------------------
-- jobs.updated_at maintenance
-- ---------------------------------------------------------------------------
-- Kept in the database rather than the application so that the column stays
-- correct no matter which writer touches the row: the JPA layer, an ETL upsert,
-- or a manual fix.
CREATE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_jobs_set_updated_at
    BEFORE UPDATE ON jobs
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
