-- Records the ETL refused to load, so that a bad input is never silently dropped.
--
-- Every rejection keeps the raw record exactly as it was read, which means a batch can
-- be triaged, corrected at source and re-run without going back to the original file.

CREATE TABLE etl_rejected_record (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    job_name         VARCHAR(100) NOT NULL,
    job_execution_id BIGINT       NOT NULL,
    rejection_reason TEXT         NOT NULL,
    original_record  TEXT         NOT NULL,
    rejected_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT pk_etl_rejected_record PRIMARY KEY (id)
);

COMMENT ON COLUMN etl_rejected_record.job_execution_id IS
    'Spring Batch JOB_EXECUTION_ID, so rejections can be traced back to the run that produced them.';
COMMENT ON COLUMN etl_rejected_record.original_record IS
    'The raw input record as read, before any transformation.';

-- Triage is always scoped to one run.
CREATE INDEX idx_etl_rejected_record_execution ON etl_rejected_record (job_execution_id);
