-- Historical skill demand, one row per skill per period.
--
-- Each row answers "among postings dated in this period, how many asked for this skill".
-- Deliberately per-period rather than cumulative: a running total only ever grows, so
-- every skill would look like it was rising and the trend would say nothing.
--
-- total_jobs is stored alongside job_count rather than recomputed at read time. It is the
-- denominator as it was for that period, so a historical share stays reproducible however
-- much the corpus grows afterwards.

CREATE TABLE skill_demand_snapshot (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    period_start DATE        NOT NULL,
    skill_id     BIGINT      NOT NULL,
    job_count    INTEGER     NOT NULL,
    total_jobs   INTEGER     NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_skill_demand_snapshot PRIMARY KEY (id),

    CONSTRAINT fk_skill_demand_snapshot_skill FOREIGN KEY (skill_id)
        REFERENCES skills (id) ON DELETE CASCADE,

    -- One row per skill per period; re-running the rebuild must not duplicate history.
    CONSTRAINT uq_skill_demand_snapshot_period_skill UNIQUE (period_start, skill_id),

    -- A skill cannot appear in more postings than the period contains. This is the
    -- invariant that would break first if the two aggregates ever drifted apart.
    CONSTRAINT ck_skill_demand_snapshot_counts CHECK (
        job_count >= 0 AND total_jobs >= 0 AND job_count <= total_jobs
    )
);

COMMENT ON COLUMN skill_demand_snapshot.period_start IS
    'First day of the month this row covers. Monthly is the finest granularity the posted date supports usefully.';
COMMENT ON COLUMN skill_demand_snapshot.job_count IS
    'Postings dated within this period that mention this skill.';
COMMENT ON COLUMN skill_demand_snapshot.total_jobs IS
    'Postings dated within this period, whatever their skills. The denominator for this row.';

-- Trends read one skill across many periods.
CREATE INDEX idx_skill_demand_snapshot_skill ON skill_demand_snapshot (skill_id, period_start);
-- Listing available periods, and windowing by date range.
CREATE INDEX idx_skill_demand_snapshot_period ON skill_demand_snapshot (period_start);
